apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cloudfront-certmanager
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["ingresses"]
  verbs: ["watch","create","get","patch","delete","list"]
