apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cloudfront-certmanager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudfront-certmanager
subjects:
- kind: ServiceAccount
  name: cloudfront-certmanager
  namespace: ops
